version: '3'
services:
  mongos_1:
    hostname: mongos-1
    image: ubuntu:16.04
    volumes:
        - ./utility/install_puppet_agent_ubuntu:/install_puppet_agent_ubuntu
    command: 
        - chmod u+x install_puppet_agent_ubuntu

  repl1_mongod1:
    hostname: repl1-mongod1
    image: ubuntu:16.04
    volumes:
        - ./utility/install_puppet_agent_ubuntu:/install_puppet_agent_ubuntu
    command: 
        - chmod u+x install_puppet_agent_ubuntu

  repl1_mongod2:
    hostname: repl1-mongod2
    image: ubuntu:16.04
    volumes:
        - ./utility/install_puppet_agent_ubuntu:/install_puppet_agent_ubuntu
    command: 
        - chmod u+x install_puppet_agent_ubuntu

  repl1_mongod3:
    hostname: repl1-mongod3
    image: ubuntu:16.04
    volumes:
        - ./utility/install_puppet_agent_ubuntu:/install_puppet_agent_ubuntu
    command: 
        - chmod u+x install_puppet_agent_ubuntu

volumes:
    mongos_1:
        driver: local
    repl1_mongod1:
        driver: local
    repl1_mongod2:
        driver: local
    repl1_mongod3:
        driver: local
