#!/usr/bin/env ruby

## @Puppetfile: this file is intended for travis ci implementation.

mod 'mongodb',
  :git => 'https://github.com/voxpupuli/puppet-mongodb.git',
  :ref => 'v2.4.1'

mod 'apt',
  :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
  :ref => '6.1.1'

mod 'stdlib',
  :git => 'https://github.com/puppetlabs/puppetlabs-stdlib.git',
  :ref => '5.1.0'
