#!/bin/bash

## local variables
PYTHON_VERSION=36
PYTHON_VERSIOND=${PYTHON_VERSION:0:1}.${PYTHON_VERSION:1:2}
TENSORFLOW_VERSION=1.10.0

## add repository
sudo yum install -y https://centos7.iuscommunity.org/ius-release.rpm
sudo yum update

## install python3
sudo yum install -y "python${PYTHON_VERSION}u"\
    "python${PYTHON_VERSION}u-libs"\
    "python${PYTHON_VERSION}u-devel"\
    "python${PYTHON_VERSION}u-pip"

echo '====================================================='
echo "python installed: $(python$PYTHON_VERSIOND -V)"
echo '====================================================='

## temporary pip3: symlink did not work
PIP3_PATH=$(which pip$PYTHON_VERSIOND)
cp -f "$PIP3_PATH" /usr/bin/pip3

## install tensorflow
sudo pip3 install tensorflow-gpu=="$TENSORFLOW_VERSION"

echo '====================================================='
echo 'tensorflow installed:'
echo "$(pip$PYTHON_VERSIOND show tensorflow-gpu)"
echo '====================================================='

## remove copied pip3
rm -f /usr/bin/pip3
